export function getHtmlElements() {
  return [
    'div',
    'span',
    'p',
    'a',
    'button',
    'input',
    'textarea',
    'select',
    'option',
    'label',
    'form',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'ul',
    'ol',
    'li',
    'table',
    'tr',
    'td',
    'th',
    'thead',
    'tbody',
    'img',
    'video',
    'audio',
    'section',
    'article',
    'header',
    'footer',
    'nav',
    'aside',
    'main',
  ]
}

export function getHtmlAttributes() {
  return [
    'accept',
    'accept-charset',
    'accesskey',
    'action',
    'align',
    'allow',
    'alpha',
    'alt',
    'aria-',
    'as',
    'async',
    'autocapitalize',
    'autocomplete',
    'autocorrect',
    'autofocus',
    'autoplay',
    'background',
    'bgcolor',
    'border',
    'capture',
    'charset',
    'checked',
    'cite',
    'class',
    'colorspace',
    'cols',
    'colspan',
    'compact',
    'content',
    'contenteditable',
    'controls',
    'coords',
    'crossorigin',
    'csp',
    'data-',
    'datetime',
    'decoding',
    'default',
    'defer',
    'dir',
    'dirname',
    'disabled',
    'download',
    'draggable',
    'elementtiming',
    'enctype',
    'enterkeyhint',
    'fetchpriority',
    'for',
    'form',
    'formaction',
    'formenctype',
    'formmethod',
    'formnovalidate',
    'formtarget',
    'headers',
    'height',
    'hidden',
    'high',
    'href',
    'hreflang',
    'http-equiv',
    'id',
    'inert',
    'inputmode',
    'integrity',
    'is',
    'ismap',
    'itemprop',
    'kind',
    'label',
    'lang',
    'language',
    'list',
    'loading',
    'loop',
    'low',
    'max',
    'maxlength',
    'media',
    'method',
    'min',
    'minlength',
    'multiple',
    'muted',
    'name',
    'nomodule',
    'nonce',
    'novalidate',
    'open',
    'optimum',
    'part',
    'pattern',
    'ping',
    'placeholder',
    'playsinline',
    'popover',
    'poster',
    'preload',
    'readonly',
    'referrerpolicy',
    'rel',
    'required',
    'reversed',
    'role',
    'rows',
    'rowspan',
    'sandbox',
    'scope',
    'selected',
    'shape',
    'size',
    'sizes',
    'slot',
    'span',
    'spellcheck',
    'src',
    'srcdoc',
    'srclang',
    'srcset',
    'start',
    'step',
    'style',
    'summary',
    'tabindex',
    'target',
    'title',
    'translate',
    'type',
    'usemap',
    'value',
    'width',
    'writingsuggestions',
    'wrap',
  ]
}

export function getPelelaAttributes() {
  return [
    'view-model',
    'bind-alt',
    'bind-class',
    'bind-content',
    'bind-enabled',
    'bind-src',
    'bind-style',
    'bind-value',
    'click',
    'enter',
    'const-',
    'for-each',
    'if',
    'index',
    'link-',
    'prop-',
  ]
}

const TAG_RESTRICTED_PELELA_ATTRIBUTES: Record<string, string[]> = {
  'bind-alt': ['img'],
  'bind-src': ['img'],
  'bind-enabled': ['input', 'select', 'button', 'textarea', 'optgroup', 'option', 'fieldset'],
  'bind-value': ['input', 'textarea', 'select'],
  enter: ['input'],
  'view-model': ['pelela', 'component'],
}

export function getPelelaAttributesForTag(tagName: string | null): string[] {
  const allAttributes = getPelelaAttributes()

  if (!tagName) return allAttributes

  return allAttributes.filter((attr) => {
    const allowedTags = TAG_RESTRICTED_PELELA_ATTRIBUTES[attr]
    if (!allowedTags) return true
    return allowedTags.includes(tagName)
  })
}
